CREATE DATABASE DBN001
    BUFFERPOOL BP1
    INDEXBP    BP1
    CCSID      EBCDIC
    STOGROUP   SYSPOOL1;

-- This should result in the Liquibase table being created as:
-- CREATE TABLE "IBMUSER".DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, 
-- FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, 
-- EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), 
-- TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10)) IN DATABASE DBN001