--liquibase formatted sql

--changeset asmith:database_001
CREATE DATABASE DBN002
    BUFFERPOOL BP1
    INDEXBP    BP1
    CCSID      EBCDIC
    STOGROUP   SYSPOOL1;

--changeset asmith:tablespace_001
CREATE TABLESPACE SSA00001
    IN DBN002
    USING STOGROUP SYSPOOL1
    PRIQTY 720 SECQTY 720
    ERASE  NO
    FREEPAGE 5 PCTFREE 15 FOR UPDATE 0
    GBPCACHE CHANGED
    TRACKMOD YES
    MAXPARTITIONS 20
    LOGGED
    DSSIZE 8 G
    SEGSIZE 32
    BUFFERPOOL BP0
    LOCKSIZE ANY
    LOCKMAX SYSTEM
    CLOSE NO
    COMPRESS NO
    CCSID      EBCDIC
    DEFINE YES
    MAXROWS 255
    INSERT ALGORITHM 0;

--changeset asmith:table_001	
CREATE TABLE ASMITH.asmith_tbl_001
     (STUDENT_ID           INTEGER NOT NULL,
      STUDENT_TYP_C        CHAR(2) FOR SBCS DATA NOT NULL,
      STUDENT_SEQ          SMALLINT NOT NULL,
      STUDENT_MAJOR        CHAR(35) FOR SBCS DATA NOT NULL,
      START_DT             DATE NOT NULL,
      LAST_MTN_DT          DATE NOT NULL,
      LAST_MTN_TM          TIME NOT NULL,
      LAST_MTN_ID          CHAR(8) FOR SBCS DATA NOT NULL,
      CONSTRAINT PRIMARY_asmith_tbl_001_01
      PRIMARY KEY (STUDENT_ID,
                   STUDENT_TYP_C),
      CONSTRAINT CI_ID0 CHECK (STUDENT_ID > 0 ))
    IN DBN002.SSA00001
    PARTITION BY SIZE
    AUDIT NONE
    DATA CAPTURE CHANGES
    WITH RESTRICT ON DROP
    CCSID      EBCDIC
    NOT VOLATILE
    APPEND NO  ;

--changeset asmith:unique_index_001
CREATE UNIQUE INDEX ASMITH.ABC001D
    ON ASMITH.asmith_tbl_001
     (STUDENT_ID            ASC,
      STUDENT_TYP_C         ASC)
    USING STOGROUP SYSPOOL1
    PRIQTY 720 SECQTY 720
    ERASE  NO
    FREEPAGE 5 PCTFREE 15
    GBPCACHE CHANGED
    CLUSTER
    COMPRESS NO
    INCLUDE NULL KEYS
    BUFFERPOOL BP1
    CLOSE NO
    COPY NO
    DEFER NO
    DEFINE YES
    PIECESIZE 2 G;

--changeset asmith:table_001_insert_001
INSERT INTO ASMITH.ASMITH_TBL_001
(STUDENT_ID, STUDENT_TYP_C, STUDENT_SEQ, STUDENT_MAJOR, START_DT, LAST_MTN_DT, LAST_MTN_TM, LAST_MTN_ID)
VALUES(2, 'R', 2, 'ECON', '2025-01-01', '2026-01-01', '2025-10-10T00:00:00.000-04:00', 'A');
