--liquibase formatted sql

--changeset asmith:tablespace_008
CREATE TABLESPACE SSA00001
    IN DBN002
    USING STOGROUP SYSPOOL1
    PRIQTY 720 SECQTY 720
    ERASE  NO
    FREEPAGE 5 PCTFREE 15 FOR UPDATE 0
    GBPCACHE CHANGED
    TRACKMOD YES
    MAXPARTITIONS 20
    LOGGED
    DSSIZE 8 G
    SEGSIZE 32
    BUFFERPOOL BP8
    LOCKSIZE ANY
    LOCKMAX SYSTEM
    CLOSE NO
    COMPRESS NO
    CCSID      EBCDIC
    DEFINE YES
    MAXROWS 255
    INSERT ALGORITHM 0;
